import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'YouMATTER - você importa',
  description: 'Generated by create next app',
  icons: {
    icon: '/heart.svg',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="bg-red-50">{children}</body>
    </html>
  )
}
